name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: testing
      run: chmod 777 run_test.bash && make test
    - name: make clean
      run: make clean
